### ISSUE TITLE
ArduCopter Instrumentation

### ISSUE THREAD

**Issue by HenriqueMisson** [anmaped/rmtld3synth#5]
Hello André,

Could you help me in the ArduCopter intrumentation code?

In the ardupilot site (http://ardupilot.org/dev/docs/code-overview-scheduling-your-new-code-to-run-intermittently.html) says just to insert the new function on the Scheduler.

So I declared a new function on ```Copter.h``` and I inserted this function on the scheduler in ```ArduCopter.cpp```.  Then, I created the function using ```void Copter::my_function()```. Is this the correct?

My main difficulty is how to call the monitor that is based on ```modules/rmtlib/nuttx```. Should this monitor be moved to ArduCopter folder?

**Comment by anmaped** [comment]
@HenriqueMisson Yes, it is the way to do.

You have to see that monitors should be compiled together when building the arducopter firmware but there is no direct dependency between instrumentation and monitoring.
Monitors will execute concurrently by the system (i.e. monitors are Posix/NuttX OS threads) and you have to be very careful since there are not much more resources left for monitoring.

**Comment by HenriqueMisson** [comment]
Thank you Andre and Happy New Year.

>Yes, it is the way to do.

So, in the ```void Copter::my_function()``` I need to write the code to be linked with the monitor or not?

> You have to see that monitors should be compiled together when building the arducopter firmware but there is no direct dependency between instrumentation and monitoring.

I didn't understand " there is no direct dependency between instrumentation and monitoring " since to monitor the target application ( in this case Arducopter execution) it is necessary to link it to the monitor, no?

> Monitors will execute concurrently by the system (i.e. monitors are Posix/NuttX OS threads) and you have to be very careful since there are not much more resources left for monitoring.
> 
This is already done according with the doc that you created, right?(https://github.com/anmaped/rmtld3synth/blob/master/doc/nuttx-ardupilot.md)

> So you have to compile the monitors as one application or even several applications (pay attention to the stack size) and trigger them all together using the NuttX init scripts to begin all the applications.

So, the monitor is compiled as an application. And I don't know how the monitor will observes exactly the events.

The NuttX init scripts is like the ``` rc.function``` based on ```px4fmu_common``` - >``` init.d``` ? This is just to initialize the nsh shell?

**Comment by anmaped** [comment]
> 
> 
> Thank you Andre and Happy New Year.
> 
> > Yes, it is the way to do.
> 
> So, in the `void Copter::my_function()` I need to write the code to be linked with the monitor or not?

No. You only have to add the events to the buffer using the methods provided by rtmlib.

> 
> > You have to see that monitors should be compiled together when building the arducopter firmware but there is no direct dependency between instrumentation and monitoring.
> 
> I didn't understand " there is no direct dependency between instrumentation and monitoring " since to monitor the target application ( in this case Arducopter execution) it is necessary to link it to the monitor, no?

The dependence is indirect i.e. the shared buffer.

> 
> > Monitors will execute concurrently by the system (i.e. monitors are Posix/NuttX OS threads) and you have to be very careful since there are not much more resources left for monitoring.
> 
> This is already done according with the doc that you created, right?(https://github.com/anmaped/rmtld3synth/blob/master/doc/nuttx-ardupilot.md)

Right.

> 
> > So you have to compile the monitors as one application or even several applications (pay attention to the stack size) and trigger them all together using the NuttX init scripts to begin all the applications.
> 
> So, the monitor is compiled as an application. And I don't know how the monitor will observes exactly the events.

The events will be consumed as soon as they are available since all the monitors are periodic.

> 
> The NuttX init scripts is like the ` rc.function` based on `px4fmu_common` - >` init.d` ? This is just to initialize the nsh shell?

Yes. More information could be found [here](http://www.nuttx.org/doku.php?id=wiki:nxinternal:initsequence).

**Comment by anmaped** [comment]
I suggest creating a tutorial about monitoring ardupilot firmware for the pixhawk platform.
For that, I suggest starting with very simple formulas.

**Comment by HenriqueMisson** [comment]
> > Thank you Andre and Happy New Year.
> > > Yes, it is the way to do.
> > 
> > 
> > So, in the `void Copter::my_function()` I need to write the code to be linked with the monitor or not?
> 
> No. You only have to add the events to the buffer using the methods provided by rtmlib.
> 
 It can be done by adding the function ```producer1``` in the "my_function" inside ArduCopter? So for this, we need to include the all files of rtmlib on ArduCopter folder.
